---
openapi: "3.0.1"
info:
  title: "12270"
  version: "1.0"
servers:
- url: "http://localhost:2160/12270/1.0"
paths:
  /:
    get:
      tags: []
      summary: ""
      description: ""
      operationId: ""
      parameters: []
      responses:
        200:
          description: "sample response"
          content:
            text/plain:
              schema: {}
components: {}
